apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: keep
  labels:
    app: mailpit
    app.kubernetes.io/part-of: shop-checkout-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:v1.20
          ports:
            - name: smtp
              containerPort: 1025
            - name: http
              containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: keep
  labels:
    app: mailpit
    app.kubernetes.io/part-of: shop-checkout-poc
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: http
      port: 8025
      targetPort: http
